POST http://localhost:8080/ingredients
Content-Type: application/json

{
  "name" : "acid",
  "price" : 322.0
}

###
POST http://localhost:8080/ingredients
Content-Type: application/json

{
  "name" : "trenabalone",
  "price" : 666.0
}

###
POST http://localhost:8080/ingredients
Content-Type: application/json

{
  "name" : "gym",
  "price" : 999.0
}

###
POST http://localhost:8080/recipes
Content-Type: application/json

{
  "complexity": "HIGH",
  "cookingTime": 9999,
  "name": "strength"
}

###
POST http://localhost:8080/recipes
Content-Type: application/json

{
  "complexity": "LOW",
  "cookingTime": 777,
  "name": "health"
}


###
POST http://localhost:8080/recipes
Content-Type: application/json

{
  "complexity": "MEDIUM",
  "cookingTime": 123,
  "name": "borsh"
}
###
PUT http://localhost:8080/recipes/1/ingredients/1

###
PUT http://localhost:8080/recipes/1/ingredients/3

###
PUT http://localhost:8080/recipes/2/ingredients/1

###
PUT http://localhost:8080/recipes/2/ingredients/2

###
PUT http://localhost:8080/recipes/3/ingredients/3

###
GET http://localhost:8080/ingredients
Accept: application/json

###
GET http://localhost:8080/dishes
Accept: application/json

###
GET http://localhost:8080/recipes
Accept: application/json

###
GET http://localhost:8080/dishes
Accept: application/json

###
POST http://localhost:8080/dishes
Content-Type: application/json

{
  "name": "health dish"
}

###
POST http://localhost:8080/recipes
Content-Type: application/json

{
  "complexity": "LOW",
  "cookingTime": 777,
  "name": "health",
  "dish": {
    "id": 1
  }
}